<<<<<<< HEAD
%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.10 (R2021a) and Database Toolbox Version 10.1 on 13-Jul-2021 22:46:05
% Make connection to database
clear all

% Make connection to database
conn = database('cti','vasanza','');

%Set query to execute on the database
%sqlquey = "SELECT voltaje FROM `cti_investigacion`.`mediciones` WHERE fecha = '2021-07-13'";
sqlquey = "SELECT * FROM `cti_investigacion`.`mediciones` WHERE fecha = '2021-07-13'";
%sqlquey = "SELECT * FROM `cti_investigacion`.`mediciones`";%toda

% Execute query and fetch results
%Extraer datos del SQL
data = fetch(conn,sqlquey);

listo = "Terminado"

% Close connection to database
close(conn)

% Clear variables
clear conn query
%%
%corrientes = table2array(data(:,2))+caldays(1:100);
%horas = datetime(table2array(data(:,1)),'InputFormat','HH:mm:ss');
%plot(horas,corrientes)

dataNew=table2array(data(:,5:11));
plot(dataNew);
=======
%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.10 (R2021a) and Database Toolbox Version 10.1 on 13-Jul-2021 22:46:05
% Make connection to database
clear all

% Make connection to database
conn = database('cti','vasanza','');

%Set query to execute on the database
%sqlquey = "SELECT voltaje FROM `cti_investigacion`.`mediciones` WHERE fecha = '2021-07-13'";
sqlquey = "SELECT * FROM `cti_investigacion`.`mediciones` WHERE fecha = '2021-07-13'";
%sqlquey = "SELECT * FROM `cti_investigacion`.`mediciones`";%toda

% Execute query and fetch results
%Extraer datos del SQL
data = fetch(conn,sqlquey);

listo = "Terminado"

% Close connection to database
close(conn)

% Clear variables
clear conn query
%%
%corrientes = table2array(data(:,2))+caldays(1:100);
%horas = datetime(table2array(data(:,1)),'InputFormat','HH:mm:ss');
%plot(horas,corrientes)

dataNew=table2array(data(:,5:11));
plot(dataNew);
>>>>>>> 3b839e76618bbefeca2457ec7b584fdf4d4f22cf
legend('voltaje','corriente','potencia','frecuencia','energia','fp','esptemp');